#!/usr/bin/env python3
"""
Alpha-GPT 논문 방식 실행
LLM을 사용한 알파 마이닝 (시가총액 상위 500개 종목)
"""

import sys
import os
from pathlib import Path
from datetime import date
import pandas as pd
from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import execute_values

# 프로젝트 루트 추가
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from alpha_gpt_kr.core import AlphaGPT

# 환경 변수 로드
load_dotenv()

def get_db_connection():
    """PostgreSQL 연결"""
    return psycopg2.connect(
        host=os.getenv('DB_HOST', '192.168.0.248'),
        port=int(os.getenv('DB_PORT', 5432)),
        database=os.getenv('DB_NAME', 'marketsense'),
        user=os.getenv('DB_USER', 'yrbahn'),
        password=os.getenv('DB_PASSWORD', '1234')
    )

def get_top_500_tickers():
    """시가총액 상위 500개 종목 티커 가져오기"""
    conn = get_db_connection()
    
    query = """
        SELECT DISTINCT ON (s.ticker)
            s.ticker
        FROM stocks s
        JOIN price_data p ON s.id = p.stock_id
        WHERE s.is_active = true
        AND p.date = (SELECT MAX(date) FROM price_data)
        AND p.close IS NOT NULL
        AND p.volume IS NOT NULL
        ORDER BY s.ticker, (p.close * p.volume) DESC
        LIMIT 500
    """
    
    df = pd.read_sql(query, conn)
    conn.close()
    
    return df['ticker'].tolist()

def save_alpha_to_db(alpha_expr, backtest_result, calc_date=None):
    """최상위 알파를 DB에 저장"""
    if calc_date is None:
        calc_date = date.today()
    
    conn = get_db_connection()
    cur = conn.cursor()
    
    try:
        # alpha_performance 테이블에 저장
        cur.execute("""
            INSERT INTO alpha_performance
            (alpha_formula, start_date, is_active, total_return, sharpe_ratio, 
             max_drawdown, notes)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (alpha_formula, start_date) DO UPDATE SET
                total_return = EXCLUDED.total_return,
                sharpe_ratio = EXCLUDED.sharpe_ratio,
                max_drawdown = EXCLUDED.max_drawdown,
                notes = EXCLUDED.notes
        """, (
            alpha_expr,
            calc_date,
            True,
            backtest_result.annual_return,
            backtest_result.sharpe_ratio,
            backtest_result.max_drawdown,
            f"IC: {backtest_result.ic:.4f}, Generated by Alpha-GPT"
        ))
        
        conn.commit()
        print(f"✅ 알파 성과 DB 저장 완료")
        
    finally:
        cur.close()
        conn.close()

def main():
    print("=" * 70)
    print("Alpha-GPT: 논문 방식 알파 마이닝")
    print("=" * 70)
    print("LLM을 사용한 자동 알파 생성 및 최적화")
    print("=" * 70)
    print()
    
    try:
        # 1. AlphaGPT 초기화
        print("📊 1단계: AlphaGPT 초기화")
        
        # LLM 선택 (OpenAI 사용)
        alpha_gpt = AlphaGPT(
            market="KRX",
            llm_provider="openai",
            model="gpt-4-turbo-preview"  # 또는 "gpt-4"
        )
        print("✅ AlphaGPT 초기화 완료 (OpenAI GPT-4)")
        
        # 2. 데이터 로드
        print("\n📊 2단계: 시가총액 상위 500개 종목 데이터 로드")
        
        top_500 = get_top_500_tickers()
        print(f"✅ 상위 500개 종목 선택")
        
        # 최근 1년 데이터 (백테스트용)
        alpha_gpt.load_data(
            universe=top_500,
            start_date="2024-02-01",
            end_date="2026-02-12",
            include_technical=False
        )
        print("✅ 데이터 로드 완료 (2024-02-01 ~ 2026-02-12)")
        
        # 3. 트레이딩 아이디어 정의
        print("\n📊 3단계: 트레이딩 아이디어")
        
        trading_idea = """
        한국 증시에서 강한 모멘텀을 보이는 종목을 찾고 싶습니다.
        
        전략 컨셉:
        1. 중기 모멘텀 (20-30일)이 강한 종목
        2. 단기 변동성 대비 수익률이 좋은 종목
        3. 거래량이 평균 이상으로 활발한 종목
        
        목표:
        - 샤프 비율 1.0 이상
        - IC (Information Coefficient) 0.01 이상
        - 최대 낙폭 -30% 이내
        
        사용 가능한 데이터:
        - close: 종가
        - open: 시가
        - high: 고가
        - low: 저가
        - volume: 거래량
        - vwap: 거래량 가중 평균 가격
        
        시간 프레임: 20-50일
        """
        
        print("✅ 아이디어:")
        print("   - 중기 모멘텀 + 낮은 변동성 + 거래량")
        print("   - 목표: Sharpe 1.0+, IC 0.01+")
        
        # 4. 알파 마이닝 실행
        print("\n📊 4단계: 알파 마이닝 (LLM + GP)")
        print("   ⏱️  예상 소요 시간: 10-30분")
        print("   (LLM API 호출 + 백테스트 반복)")
        print()
        
        result = alpha_gpt.mine_alpha(
            idea=trading_idea,
            num_seeds=10,          # LLM이 생성할 초기 알파 개수
            enhancement_rounds=20,  # GP 진화 세대 수
            mode="autonomous",      # 자동 모드
            top_n=5                # 상위 5개 반환
        )
        
        # 5. 결과 출력
        print("\n" + "=" * 70)
        print("✅ 알파 마이닝 완료!")
        print("=" * 70)
        
        print(f"\n🏆 최상위 알파:")
        print(f"   공식: {result.top_alphas[0][0]}")
        print(f"   IC: {result.best_ic:.4f}")
        print(f"   Sharpe: {result.best_sharpe:.2f}")
        
        print(f"\n📊 상위 5개 알파:")
        for i, (expr, br) in enumerate(result.top_alphas, 1):
            print(f"\n   {i}. {expr[:80]}...")
            print(f"      IC: {br.ic:.4f} | Sharpe: {br.sharpe_ratio:.2f} | "
                  f"Return: {br.annual_return:.2%} | MDD: {br.max_drawdown:.2%}")
        
        print(f"\n📝 분석 리포트:")
        print(result.analysis_report)
        
        # 6. DB 저장
        print("\n📊 5단계: 최상위 알파 DB 저장")
        
        best_expr = result.top_alphas[0][0]
        best_result = result.top_alphas[0][1]
        
        save_alpha_to_db(best_expr, best_result)
        
        print("\n" + "=" * 70)
        print("🎉 Alpha-GPT 논문 방식 실행 완료!")
        print("=" * 70)
        print(f"\n다음 단계:")
        print(f"1. 생성된 알파를 포트폴리오 구성에 사용")
        print(f"2. 실전 매매 전 추가 백테스트 권장")
        print(f"3. 대시보드에서 성과 모니터링")
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
